### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [GA114/tc359p11#1]
Looks mostly very good, except I got a 404 when trying to sign out, due to [this line](https://github.com/GA114/tc359p11/blob/master/config/routes.rb#L4) not quite using the right HTTP method (GET instead of DELETE). Can you update this?

**Comment by GA114** [comment]
[Oops](https://github.com/GA114/tc359p11/commit/527fafd26809bb73ee2d0d6b1d9f8e95c0916bd2).

**Comment by chrisvfritz** [comment]
:+1: Wonderful!
